# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/nks/Desktop/test_725/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/nks/Desktop/test_725/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/nks/Desktop/test_725/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/MAIN_CLK/MAIN_CLK.dcp
set_property used_in_implementation false [get_files C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/MAIN_CLK/MAIN_CLK.dcp]
read_verilog -library xil_defaultlib C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/new/led.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/constrs_1/new/led.xdc]


synth_design -top led -part xc7a35tcsg324-2


write_checkpoint -force -noxdef led.dcp

catch { report_utilization -file led_utilization_synth.rpt -pb led_utilization_synth.pb }
