# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/led.xdc

# Block Designs: bd/module_ads7056/module_ads7056.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056 || ORIG_REF_NAME==module_ads7056}]

# IP: bd/module_ads7056/ip/module_ads7056_ADS7056_0_0/module_ads7056_ADS7056_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_ADS7056_0_0 || ORIG_REF_NAME==module_ads7056_ADS7056_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_me18_0_0/module_ads7056_me18_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_me18_0_0 || ORIG_REF_NAME==module_ads7056_me18_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_led_0_0/module_ads7056_led_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_led_0_0 || ORIG_REF_NAME==module_ads7056_led_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_clk_wiz_0_0/module_ads7056_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_clk_wiz_0_0 || ORIG_REF_NAME==module_ads7056_clk_wiz_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_util_ds_buf_0_0/module_ads7056_util_ds_buf_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_util_ds_buf_0_0 || ORIG_REF_NAME==module_ads7056_util_ds_buf_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_microblaze_0_0/module_ads7056_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_microblaze_0_0 || ORIG_REF_NAME==module_ads7056_microblaze_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_dlmb_v10_0/module_ads7056_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_dlmb_v10_0 || ORIG_REF_NAME==module_ads7056_dlmb_v10_0}]

# IP: bd/module_ads7056/ip/module_ads7056_ilmb_v10_0/module_ads7056_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_ilmb_v10_0 || ORIG_REF_NAME==module_ads7056_ilmb_v10_0}]

# IP: bd/module_ads7056/ip/module_ads7056_dlmb_bram_if_cntlr_0/module_ads7056_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==module_ads7056_dlmb_bram_if_cntlr_0}]

# IP: bd/module_ads7056/ip/module_ads7056_ilmb_bram_if_cntlr_0/module_ads7056_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==module_ads7056_ilmb_bram_if_cntlr_0}]

# IP: bd/module_ads7056/ip/module_ads7056_lmb_bram_0/module_ads7056_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_lmb_bram_0 || ORIG_REF_NAME==module_ads7056_lmb_bram_0}]

# IP: bd/module_ads7056/ip/module_ads7056_microblaze_0_axi_periph_0/module_ads7056_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_microblaze_0_axi_periph_0 || ORIG_REF_NAME==module_ads7056_microblaze_0_axi_periph_0}]

# IP: bd/module_ads7056/ip/module_ads7056_microblaze_0_axi_intc_0/module_ads7056_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_microblaze_0_axi_intc_0 || ORIG_REF_NAME==module_ads7056_microblaze_0_axi_intc_0}]

# IP: bd/module_ads7056/ip/module_ads7056_microblaze_0_xlconcat_0/module_ads7056_microblaze_0_xlconcat_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_microblaze_0_xlconcat_0 || ORIG_REF_NAME==module_ads7056_microblaze_0_xlconcat_0}]

# IP: bd/module_ads7056/ip/module_ads7056_mdm_1_0/module_ads7056_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_mdm_1_0 || ORIG_REF_NAME==module_ads7056_mdm_1_0}]

# IP: bd/module_ads7056/ip/module_ads7056_rst_clk_wiz_0_120M_0/module_ads7056_rst_clk_wiz_0_120M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_rst_clk_wiz_0_120M_0 || ORIG_REF_NAME==module_ads7056_rst_clk_wiz_0_120M_0}]

# IP: bd/module_ads7056/ip/module_ads7056_axi_gpio_0_0/module_ads7056_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_axi_gpio_0_0 || ORIG_REF_NAME==module_ads7056_axi_gpio_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_util_ds_buf_1_0/module_ads7056_util_ds_buf_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_util_ds_buf_1_0 || ORIG_REF_NAME==module_ads7056_util_ds_buf_1_0}]

# IP: bd/module_ads7056/ip/module_ads7056_axi_quad_spi_0_0/module_ads7056_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_axi_quad_spi_0_0 || ORIG_REF_NAME==module_ads7056_axi_quad_spi_0_0}]

# IP: bd/module_ads7056/ip/module_ads7056_xbar_0/module_ads7056_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_xbar_0 || ORIG_REF_NAME==module_ads7056_xbar_0}]

# IP: bd/module_ads7056/ip/module_ads7056_auto_pc_1/module_ads7056_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_auto_pc_1 || ORIG_REF_NAME==module_ads7056_auto_pc_1}]

# IP: bd/module_ads7056/ip/module_ads7056_auto_pc_0/module_ads7056_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==module_ads7056_auto_pc_0 || ORIG_REF_NAME==module_ads7056_auto_pc_0}]

# XDC: bd/module_ads7056/module_ads7056_ooc.xdc
