# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7a35tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.cache/wt [current_project]
set_property parent.project_path D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/hdl/module_ads7056_wrapper.v
add_files D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/module_ads7056.bd
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_clk_wiz_0_0/module_ads7056_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_clk_wiz_0_0/module_ads7056_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_clk_wiz_0_0/module_ads7056_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_util_ds_buf_0_0/module_ads7056_util_ds_buf_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_0/module_ads7056_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_0/module_ads7056_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_0/module_ads7056_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_dlmb_v10_0/module_ads7056_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_dlmb_v10_0/module_ads7056_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_ilmb_v10_0/module_ads7056_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_ilmb_v10_0/module_ads7056_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_dlmb_bram_if_cntlr_0/module_ads7056_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_ilmb_bram_if_cntlr_0/module_ads7056_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_lmb_bram_0/module_ads7056_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_axi_intc_0/module_ads7056_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_axi_intc_0/module_ads7056_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_microblaze_0_axi_intc_0/module_ads7056_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_mdm_1_0/module_ads7056_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_mdm_1_0/module_ads7056_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_mdm_1_0/module_ads7056_mdm_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_rst_clk_wiz_0_120M_0/module_ads7056_rst_clk_wiz_0_120M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_rst_clk_wiz_0_120M_0/module_ads7056_rst_clk_wiz_0_120M_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_rst_clk_wiz_0_120M_0/module_ads7056_rst_clk_wiz_0_120M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_gpio_0_0/module_ads7056_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_gpio_0_0/module_ads7056_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_gpio_0_0/module_ads7056_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_util_ds_buf_1_0/module_ads7056_util_ds_buf_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_quad_spi_0_0/module_ads7056_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_quad_spi_0_0/module_ads7056_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_quad_spi_0_0/module_ads7056_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_axi_quad_spi_0_0/module_ads7056_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_xbar_0/module_ads7056_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_auto_pc_1/module_ads7056_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/ip/module_ads7056_auto_pc_0/module_ads7056_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/module_ads7056_ooc.xdc]
set_property is_locked true [get_files D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/sources_1/bd/module_ads7056/module_ads7056.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/constrs_1/new/led.xdc
set_property used_in_implementation false [get_files D:/GIT_Project/20171031/TE_725_1023_mb/project_1/project_1.srcs/constrs_1/new/led.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top module_ads7056_wrapper -part xc7a35tcsg324-2 -resource_sharing off


write_checkpoint -force -noxdef module_ads7056_wrapper.dcp

catch { report_utilization -file module_ads7056_wrapper_utilization_synth.rpt -pb module_ads7056_wrapper_utilization_synth.pb }
