# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK.xci
# IP: The module: 'SUB_CLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: C:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK.xci
# IP: The module: 'SUB_CLK' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/Users/nks/Desktop/test_725/project_1/project_1.srcs/sources_1/ip/SUB_CLK/SUB_CLK_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'SUB_CLK'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
